# Generated by Django 3.2.5 on 2021-12-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojects',
            name='image',
            field=models.FilePathField(path='/img'),
        ),
    ]
