# Generated by Django 3.2.5 on 2021-12-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0002_alter_myprojects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojects',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
