# Generated by Django 3.2.5 on 2021-12-19 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0003_alter_myprojects_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('skills', models.TextField()),
                ('profilepic', models.ImageField(upload_to='authorpics')),
            ],
        ),
        migrations.AddField(
            model_name='myprojects',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myprojects.author'),
        ),
    ]
