# Generated by Django 3.2.5 on 2021-12-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0004_auto_20211219_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprojects',
            name='github',
            field=models.TextField(max_length=60, null=True),
        ),
    ]
