# Generated by Django 3.2.5 on 2021-12-20 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0005_myprojects_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_info', models.TextField()),
                ('comment_date', models.DateField()),
                ('myprojects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myprojects.myprojects')),
            ],
        ),
    ]
